name: Setup dependencies
description: Perform standard setup and install dependencies using pnpm.
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3
    - name: Install node
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: 22.16.0
    - name: Install node dependencies
      shell: bash
      run: pnpm install
