name: Check

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  types:
    name: Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
      - name: Setup dependencies
        uses: ./.github/actions/setup
      - run: tsc --noEmit

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
    - uses: actions/checkout@v4
    - name: Setup dependencies
      uses: ./.github/actions/setup
    - run: pnpm lint

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 6
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install dependencies
  #       uses: ./.github/actions/setup
  #     - run: pnpm test

  ## This is for codegen, unused rn
  # drift:
  #   name: Check Source Drift
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 6
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup dependencies
  #       uses: ./.github/actions/setup
  #     - name: Build Project
  #       run: pnpm build
  #     - name: Check source state
  #       run: git add src && git diff-index --cached HEAD --exit-code src
