name: Build + Release Docker Image
on:
  workflow_call:
    inputs:
      image-tags:
          required: true
          type: string
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # Req for multi platform builds
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./ci/dockerfile
                push: true
                tags: ${{ inputs.image-tags }}
                cache-from: type=registry,ref=${{ vars.DOCKERHUB_IMAGE }}:cache
                cache-to: type=registry,ref=${{ vars.DOCKERHUB_IMAGE }}:cache,mode=max
                platforms: linux/amd64,linux/arm64
