name: Release Package
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    name: "Changesets: Create Release PR || npm.js Publish"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm exec changeset version
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      published: ${{ steps.changesets.outputs.published }}
  dockerhub:
    needs: changesets
    name: Publish DockerHub Images
    uses: ./.github/workflows/docker.yml
    if: ${{ needs.changesets.outputs.published == 'true' }}
    secrets: inherit
    with:
      image-tags: |
        ${{ vars.DOCKERHUB_IMAGE }}:latest
        ${{ vars.DOCKERHUB_IMAGE }}:development
        ${{ vars.DOCKERHUB_IMAGE }}:${{ github.ref_name }}
